version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0  # Use the appropriate image for your Java project

    steps:
      - checkout  # Checkout the code

      # Cache Maven dependencies to speed up builds
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}

      # Install project dependencies with Maven
      - run:
          name: Install dependencies
          command: mvn dependency:go-offline

      # Save the new cache
      - save_cache:
          key: v1-dependencies-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2/repository

      # Run the Cucumber tests using Maven
      - run:
          name: Run Cucumber tests
          command: mvn test

      # Store test results for later use
      - store_test_results:
          path: target/surefire-reports

      # Save test artifacts (e.g., reports) for later use
      - store_artifacts:
          path: target/surefire-reports
          destination: test-results

workflows:
  version: 2
  build_and_test:
    jobs:
      - build